# Generated by Django 4.1.7 on 2023-03-08 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateTimeField()),
                ('date_of_job_start', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('population', models.IntegerField()),
                ('date_of_foundation', models.DateTimeField()),
                ('mayor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.mayor')),
            ],
        ),
    ]
