# Generated by Django 4.1.7 on 2023-03-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_alter_mayor_date_of_job_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='date_of_foundation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mayor',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
