# Generated by Django 4.1.7 on 2023-03-08 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_alter_city_date_of_foundation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities.city'),
        ),
    ]
